apiVersion: v1
kind: Service
metadata:
  name: phase5-service
  namespace: phase5
spec:
  type: NodePort
  selector:
    app: phase5-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007
